import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

// import products from '../products.json';
import { fromImageToUrl, API_URL } from '../utils/url';
import { twoDecimals } from '../utils/format';

export default function Home({ products }) {
  console.log(products);
  return (
    <div>
      <Head>
        <title>Ecommerce NextJs + Strapi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head >

      {products.data.map(product => (
        <Link href={`/products/${product.attributes.slug}`}>
          <a>
            <div className={styles.product}>
              <div className={styles.product__row}>
                <div className={styles.product__col}>
                  <img src={fromImageToUrl(product.attributes.image.data.attributes)} alt="product" />
                </div>
                <div className={styles.product__col}>
                  {product.attributes.name} ${twoDecimals(product.attributes.price)}
                </div>
              </div>
            </div>
          </a>
        </Link>
      ))}
    </div >
  );
}

export async function getStaticProps() {
  // Fetch
  const product_res = await fetch(`${API_URL}/api/products?populate=*`);
  const products = await product_res.json();

  // Retrun
  return {
    props: {
      products
    }
  };
}
